directory:
  - .
branch: main
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- all
mask: []
secrets-scan-file-type: []
summary-position: top
skip-check:
  - CKV_TF_1                 # not supported by terraform registry
  - CKV_CIRCLECIPIPELINES_2  # image is built by the maintainer of this pipeline
  - CKV2_AWS_38
  - CKV2_AWS_39
  - CKV_AWS_355              # Using AWS supplied eks add-ons sa policy