---
version: 2.1

orbs:
  terraform: twdps/terraform@3.0.1
  kube: twdps/kube-ops@1.1.2
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@4.1.0

globals:
  - &context empc-lab
  - &executor-image twdps/circleci-infra-aws:alpine-7.5.0

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      account:
        type: string
    steps:
      - op/env:
          env-file: op.<< parameters.account >>.env
      - op/tpl:
          tpl-path: environments
          tpl-file: << parameters.account >>.auto.tfvars.json
      - terraform/terraformrc
      - do/bash-functions

  host-zone-integration-test:
    description: generate environment credentials and configuration from templates
    parameters:
      account:
        type: string
    steps:
      - run:
          name: integration test nonprod account
          command: bash scripts/hosted_zone_test.sh << parameters.account >> nonprod
      - run:
          name: integration test prod account
          command: bash scripts/hosted_zone_test.sh << parameters.account >> prod

  teams-and-gateways-integration-tests:
    parameters:
      cluster:
        description: cluster and tf workspace name
        type: string
    steps:
      - run:
          name: run control plane services integration tests
          command: bats test/services_integration_tests.bats
      - run:
          name: run gateway functional test
          command: bash scripts/gateway_functional_test.sh << parameters.cluster >>

jobs:

  deploy team and gateway configuration:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster name
        type: string
    steps:
      - checkout
      - set-environment:
          account: << parameters.cluster >>
      - kube/op-config:
          op-value: empc-lab/psk-aws-<< parameters.cluster >>/kubeconfig-base64
      - run:
          name: install external-dns
          command: bash scripts/install_external_dns.sh << parameters.cluster >>
      # - run:
      #     name: deploy cluster certificate issuer
      #     command: |
      #       bash scripts/define_certificate_issuer.sh << parameters.cluster >>
      #       bash scripts/deploy_certificate_issuer.sh << parameters.cluster >>
      # - run:
      #     name: deploy cluster defautl gateways
      #     command: bash scripts/deploy_gateways.sh << parameters.cluster >>

      # - teams-and-gateways-integration-tests:
      #      cluster: << parameters.cluster >>

workflows:
  version: 2

  hosted-zones and preview environment configuration:
    jobs:
      - terraform/static-analysis:
          name: terraform static code analysis
          context: *context
          executor-image: *executor-image
          workspace: sbx-i01-aws-us-east-1
          tflint-scan: true
          tflint-provider: aws
          trivy-scan: true
          before-static-analysis:
            - op/env:
                env-file: op.sbx-i01-aws-us-east-1.env
          filters: *on-push-main

      - terraform/plan:
          name: service account change plan
          context: *context
          executor-image: *executor-image
          workspace: sbx-i01-aws-us-east-1
          checkov-scan: true
          before-plan:
            - set-environment:
                account: sbx-i01-aws-us-east-1
          filters: *on-push-main

      # - approve:
      #     name: approve hosted-zones change plan
      #     type: approval
      #     requires:
      #       - static code analysis
      #       - hosted-zones change plan
      #     filters: *on-push-main

      # - terraform/apply:
      #     name: hosted-zones release
      #     context: *context
      #     executor-image: *executor-image
      #     workspace: state
      #     before-apply:
      #       - set-environment:
      #           account: multiaccount
      #     after-apply:
      #       - host-zone-integration-test:
      #           account: multiaccount
      #       - do/slack-bot:
      #           channel: lab-events
      #           message: Release psk-platform-simple-teams-and-ns hosted-zones
      #           include-link: true
      #           include-tag: true
      #     requires:
      #        - approve hosted-zones change plan
      #     filters: *on-push-main

      # - deploy team and gateway configuration:
      #     name: deploy sbx team and gateway config
      #     context: *context
      #     cluster: sbx-i01-aws-us-east-1
      #     # requires:
      #     #   - hosted-zones release
      #     filters: *on-push-main


  # standard enviro:
  #   jobs:


      # apply cluster configuration
      # - external-dns instances
      # - gateways/certificates
      # - namespaces with quotas for list of teams, only need be prod for this example

      # - do/release:
      #     name: generate release notes
      #     context: *context
      #     on-tag: true
      #     before-release:
      #       - op/env:
      #           env-file: op.env
      #     requires:
      #       - hosted-zones release
      #     filters: *on-tag-main
