---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $team-$namespace-team-rolebinding
  namespace: $team-$namespace
subjects:
  - kind: Group
    name: ThoughtWorks-DPS/$team
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: $team-$namespace-team-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-preview-team-role
  namespace: demo-preview
rules:
  - apiGroups: ["*"]
    resources:
      - configmaps
      - cronjobs
      - deployments
      - endpoints
      - events
      - horizontalpodautoscalers
      - jobs
      - leases
      - limitranges
      - namespaces
      - networkpolicies
      - nodes
      - nodeclaims
      - persistentvolumeclaims
      - persistentvolumes
      - poddisruptionbudgets
      - pods
      - replicasets
      - replicationcontrollers
      - resourcequotas
      - services
      - statefulsets
      - storageclasses
      - validatingwebhookconfigurations
      - volumeattachments
    verbs: ["get", "watch", "list"]